package com.uttara.threads;

public class TestPrime {

	public static void main(String[] args) {
		try {
			
		PrimeNumberJob job1 = new PrimeNumberJob(1000000000);
		PrimeNumberJob job2 = new PrimeNumberJob(1000000000);
		Thread t1 = new Thread(job1);
		Thread t2 = new Thread(job2);
		t1.setName("PrimeGen1");
		t1.setName("PrimeGen2");
		t1.start();
		t2.start();
		t1.join(); // main thread gets to become blocked until t1 dies
		t2.join();
		
		System.out.println("t1 state = "+t1.getState().toString());
		System.out.println("t2 state = "+t2.getState().toString());
		System.out.println("Prime number generated by t1 = "+job1.getPrimeNum());
		System.out.println("Prime number generated by t2 = "+job2.getPrimeNum());
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

}
